### ISSUE TITLE
I get EGL_NOT_INITIALIZED when calling eglChooseConfig(...) in test_egl and test_glesv2

### ISSUE THREAD

**Issue by maribu** [libhybris/libhybris#115]
Hi, there!

I compiled the latest libhybris version using these android headers http://ubuntuone.com/6PwRhU0CN1MZFrBUNJFnHL and using this /system folder http://ubuntuone.com/64JdjdWVq9F2E5p6gMQE1J (both files are .tar.xz archives). When I run test_egl or test_glesv2 I get assertion errors at test_egl.c:51 or test_glesv2:112. In both cases I do get EGL_NOT_INITIALIZED (0x3001) instead of EGL_SUCCESS (0x3000) after calling eglChoseConfig.

I'm using EGL_PLATFORM=fbdev, have read and write access to /dev/ump (and modules ump and disp_ump are loaded).

My distribution is Arch Linux (armv7 with hard float, kernel version is 3.0.57) running on a Cubieboard.

Has anyone an idea what went wrong?

Thanks for your help!

Regards,
maribu

**Comment by seisdr** [comment]
This issue is older than my mom
