### ISSUE TITLE
test_gps breaks the build.

### ISSUE THREAD

**Issue by ChALkeR** [libhybris/libhybris#185]
Building master on mk802ii, debian jessie.

Used `./autogen.sh --prefix=/opt/hybris --with-android-headers=/opt/android-headers --enable-wayland --enable-mesa`.

```
  CC       test_gps-test_gps.o
test_gps.c: In function 'agps_handle_status_callback':
test_gps.c:290:51: error: 'AGPS_APN_BEARER_IPV4' undeclared (first use in this function)
         AGps->data_conn_open(AGPS_TYPE_SUPL, apn, AGPS_APN_BEARER_IPV4);
                                                   ^
test_gps.c:290:51: note: each undeclared identifier is reported only once for each function it appears in
test_gps.c:290:9: warning: passing argument 1 of 'AGps->data_conn_open' makes pointer from integer without a cast [enabled by default]
         AGps->data_conn_open(AGPS_TYPE_SUPL, apn, AGPS_APN_BEARER_IPV4);
         ^
test_gps.c:290:9: note: expected 'const char *' but argument is of type 'int'
test_gps.c:290:9: error: too many arguments to function 'AGps->data_conn_open'
make[2]: *** [test_gps-test_gps.o] Error 1
make[2]: Leaving directory `/root/hybris/android/libhybris/hybris/tests'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/hybris/android/libhybris/hybris'
make: *** [all] Error 2
```

Commenting out test_gps from hybris/tests/Makefile.am helps, and everything compiles nicely.

**Comment by vicamo** [comment]
@zhanghongce have the same problem compiling with android headers for API level 16. Configured with `./hybris/autogen.sh --prefix=/usr --with-default-egl-platform=hwcomposer --enable-debug --enable-trace --with-default-hybris-ld-library-path=/system/lib:/vendor/lib --with-android-headers=/home/vicamo/work/android/aosp/platform/headers/android-16`. Android header for API level 17 or above is fine. Nothing to do with wayland here.

**Comment by vicamo** [comment]
It turns out __AGPS_APN_BEARER_IPV4__ is actually a Qualcomm extension, not part of AOSP. I can have a fix for this, but don't know how to deal with the build with qualcomm platform. Probably there should be a switch that explicitly turns on qualcomm GPS support, but that means build failure on systems with Android API level 16 or older that upstream developers are(were?) working on.
