### ISSUE TITLE
Bionic patch for lollipop ( 5.0.0 )?

### ISSUE THREAD

**Issue by ycavan** [libhybris/libhybris#284]
Is it just me or is there no Bionic patch for lollipop? 

Also, would this kernel boot up Android after patching Bionic?  or do we just need to compile it to get the system directory?

My goal is to access the PowerVR Rogue gpu drivers in the Asus Zenfone 2 from an Arch x86_64 chroot.

**Comment by mac-l1** [comment]
See https://code-review.phablet.ubuntu.com/gitweb?p=aosp/platform/bionic.git;a=heads
I used this to patch bionic for 5.1.1

**Comment by morphis** [comment]
The patches are the same as before and something like https://code-review.phablet.ubuntu.com/gitweb?p=aosp/platform/bionic.git;a=shortlog;h=refs/heads/personal/w-ondra/phablet-5.1.1_r5 is a good reference.
