### ISSUE TITLE
dlopen() a library that links to libGLESv2 crashes on first call from library to a GLES function

### ISSUE THREAD

**Issue by kdub** [libhybris/libhybris#315]
If you dlopen() a library that links to libGLESv2, the first call from that library to the libGLESv2 will segfault on an ifunc. (My particular case was glCreateShader). One workaround is to LD_PRELOAD the glesv2 library.

**Comment by kdub** [comment]
working on fix...

**Comment by morphis** [comment]
There is also a difference between what we have right now in Ubuntu and what we have upstream. See https://paste.ubuntu.com/16355905/ which was introduced by https://github.com/libhybris/libhybris/commit/a38512b703c4a3af6a3a34276946262c4bb46393

Looks to me like that would fix your problem.

**Comment by kdub** [comment]
It seems what was happening was that the linker was resolving the symbols before the _libglesv2 library was opened by the library's constructor. This put 0x0 in the plt entries for the functions that were indirectly loaded. The attached fix seems like it would resolve the problem. Can probably close this issue.

**Comment by morphis** [comment]
@kdub Imported this fix now into our Ubuntu tree and will be available with the next release.
