### ISSUE TITLE
hybris breaks on Android M

### ISSUE THREAD

**Issue by ghosalmartin** [libhybris/libhybris#318]
Breaks on Android M, tested with Nexus 5. Linker has been changed.

**Comment by morphis** [comment]
We have Android 6 based linker in Ubuntu working already. I just didn't found the time yet to propose it upstream as it has some Ubuntu specific changes in it. See https://git.launchpad.net/~libhybris-maintainers/libhybris/+git/libhybris/ for details.

**Comment by ghosalmartin** [comment]
Ah awesome, I'll give that a look :D

**Comment by ghosalmartin** [comment]
this has been handled by the new pr and merge
