### ISSUE TITLE
About libhybris support android6.0

### ISSUE THREAD

**Issue by Lyric1985** [libhybris/libhybris#320]
libhybris support android6.0?Do you need to add libc++ support to libhybris?

**Comment by morphis** [comment]
The upstream libhybris does not support Android 6.0 yet. Please have a look at https://code.launchpad.net/~libhybris-maintainers/libhybris/+git/libhybris/+ref/master That comes with full support for Android 6 and even 64 bit support.

**Comment by Lyric1985** [comment]
Thank you so much.

**Comment by Lyric1985** [comment]
Thank you so much.

**Comment by Lyric1985** [comment]
Hi,Simon Fels,

I am now running libribris on ubuntu andriod graphics library, in libhybris
implementation, because the thread mali-hist-dump will cause a process
error, so I quit the thread mali-hist-dump to solve this problem, which may
Performance is affected, the thread mali-hist-dump in the library what role?
If I do not exit the thread mali-hist-dump, by tracking the PC address, the
program is found in the function malioc_release_outputs segment error,
there are other ways to solve this problem?

BR.

Lyric.

2016-09-28 16:31 GMT+08:00 Simon Fels <notifications@github.com>:
