### ISSUE TITLE
Incorrect TLS slot values

### ISSUE THREAD

**Issue by IlyaBizyaev** [libhybris/libhybris#359]
Hello! :)

I am porting Halium to an x86 phone and facing many issues related to architecture support. One of them is in libhybris: the library uses custom TLS slot values that do not work with x86.

https://github.com/libhybris/libhybris/blob/master/hybris/common/mm/bionic/libc/private/bionic_tls.h

So far me and all the other x86 port developers have been using their own values, but now I'm facing weird issues and think these constants may be the problem. What are these slots, what are they supposed to affect, why do they need to be changed for libhybris and __how__ do I need to change them to be correct?

**Comment by krnlyng** [comment]
can you elaborate weird issues you see a bit more?

do you have this patch? https://github.com/mer-hybris/android_bionic/commit/1f5efaff191884a6cd4c2f80ab878f89354fe857

**Comment by IlyaBizyaev** [comment]
This patch changes values to be as in the current file revision I linked to,  and these values cause segmentation faults on Intel devices due to libc stack corruption. One of the possible workarounds (and the one I use now) is:
```
TLS_SLOT_ERRNO = 6,
TLS_SLOT_OPENGL_API = 7,
TLS_SLOT_OPENGL = 8,
TLS_SLOT_STACK_GUARD = 5,
TLS_SLOT_DLERROR = 9, // this one was empty before
```
And even though executables do not crash immediately now, there are occasional debugger messages in backtraces saying that there could be a stack corruption. But most importantly, I can't get my PowerVR graphics card to work, as the kernel gets empty command pointers. I lack experience, so that could obviously happen for any other reason, but these values are of suspect :)

**Comment by IlyaBizyaev** [comment]
Slot values in libhybris are unused, fixed in Halium bionic.
