### ISSUE TITLE
Whether to support android 8(Android Oreo)?

### ISSUE THREAD

**Issue by lyric999** [libhybris/libhybris#378]
Hi,

Whether to support android 8(Android Oreo)?

**Comment by mlehtima** [comment]
Android 7 linker works mostly with android 8 also, some fixes might be needed though. I have also ported the hybris patches to android 8 linker but that is not yet tested.

**Comment by lyric999** [comment]
Hi,mlehtima,

Can you release the android 8 supported patches? I mainly want to support Qualcomm platform.

**Comment by phrack-lp** [comment]
Hi all,
Is there a android o linker's patches?

**Comment by zspking** [comment]
i am working to support android O .   
"android o linker's patches" pass , because“dlopen dlsym ”just success 。
but “test_egl test_glesv2” display is nothing . 
so indicate "fd_dev / hwcomposer " just not worked ？？？

**Comment by zspking** [comment]
is there anyone do this work ， please mail to me zsp95@126.com

**Comment by lyric999** [comment]
@mlehtima,android o linker's patches available?

**Comment by lyric999** [comment]
@mlehtima Thank you! Very much looking forward to.you have debugged Qualcomm's adreno GPU? Is there anything different? I am using an android6.0 linker, which returns EGL_NOT_INITIALIZED when calling the eglGetConfigs method,but before calling eglInitialize, eglGetDisplay is successful.

**Comment by lyric999** [comment]
@mlehtima To implement android 8 support, do you have to implement hwc2? How do I add support to libhybris? I don't understand how gralloc1 is related to fb. Gralloc has operations like open(/dev/fb0), but in gralloc1 could not find it.

**Comment by mlehtima** [comment]
As mentioned in the Android 8 support pull request https://github.com/libhybris/libhybris/pull/388 hwc2 is not yet implemented. Currently we use Android surfaceflinger to get graphics working.

**Comment by Lyric1985** [comment]
Pull request  #388 <https://github.com/libhybris/libhybris/pull/388>
Whether surfaceflinger graphics working is supported?

2018-06-18 23:39 GMT+08:00 Matti Lehtimäki <notifications@github.com>:

**Comment by lyric999** [comment]
@mlehtima The problem I have now is that test_egl_configs can run successfully, but nothing can be seen when test_glesv2 is executed. The method of the queueBuffer of ANativeWindow is not called, and the open method of fb driver is not invoked. Under what conditions, the queueBuffer method of ANativeWindow will be executed. Where is the operation of open fb executed?

**Comment by krnlyng** [comment]
@lyric999 in android 8 there is no framebuffer module anymore.

hwcomposer is the only thing you can use, and android 8 uses a new hwcomposer API, hwc2 which is not implemented yet.

we currently use surfaceflinger to draw to the screen: https://github.com/mer-hybris/qt5-qpa-surfaceflinger-plugin

**Comment by lyric999** [comment]
@mlehtima Thank you very much, I will try it.

**Comment by lyric999** [comment]
@mlehtima Is there a demo code that directly calls hwc2 to implement drawing? Just like hwc1, I want to implement it by hwc2. I am looking at how to implement it.

**Comment by krnlyng** [comment]
@lyric999 

you have to look at hwcomposer documentation (and headers in the sources) and surfaceflinger in order to figure out how to use HWC2.

I am not aware of any public tests or examples for HWC2.

**Comment by yujun190834** [comment]
@lyric999 
How was the hwc2 trial going?
Does it work successfully?

**Comment by lyric999** [comment]
@yujun190834 
I haven't verified the latest version yet, but I think it should be possible.
