### ISSUE TITLE
Error when running make

### ISSUE THREAD

**Issue by e-cl** [libhybris/libhybris#414]
Hello.
Please could you help me.
I have android 5.0.2 Samsung tablet with snapdragon 400, kernel 3.4. Using Linux deploy i run Ubuntu 18 in chroot. I want to try libhybris to get gpu hardware acceleration in Ubuntu. I took headers from here 
https://android.googlesource.com/platform/
for android 5.0.2_r3. I'm not sure about this r3 however, don't know if it's a correct one.
Autoconf returned no errors, so i type make and this is what happens.
Could comebody help me with this? Thank you.

root@localhost:/home/eclipse/lh/libhybris/hybris# make
make  all-recursive
make[1]: Entering directory '/home/eclipse/lh/libhybris/hybris'
Making all in include
make[2]: Entering directory '/home/eclipse/lh/libhybris/hybris/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/eclipse/lh/libhybris/hybris/include'
Making all in common
make[2]: Entering directory '/home/eclipse/lh/libhybris/hybris/common'
Making all in jb
make[3]: Entering directory '/home/eclipse/lh/libhybris/hybris/common/jb'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/eclipse/lh/libhybris/hybris/common/jb'
make[3]: Entering directory '/home/eclipse/lh/libhybris/hybris/common'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/eclipse/lh/libhybris/hybris/common'
make[2]: Leaving directory '/home/eclipse/lh/libhybris/hybris/common'
Making all in properties
make[2]: Entering directory '/home/eclipse/lh/libhybris/hybris/properties'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/eclipse/lh/libhybris/hybris/properties'
Making all in hardware
make[2]: Entering directory '/home/eclipse/lh/libhybris/hybris/hardware'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/eclipse/lh/libhybris/hybris/hardware'
Making all in gralloc
make[2]: Entering directory '/home/eclipse/lh/libhybris/hybris/gralloc'
  CC       libgralloc_la-gralloc.lo
In file included from /home/eclipse/lh/hybris_headers/hardware/gralloc.h:31:0,
                 from gralloc.c:5:
/home/eclipse/lh/hybris_headers/hardware/fb.h:128:51: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
     int (*post)(struct framebuffer_device_t* dev, buffer_handle_t buffer);
                                                   ^~~~~~~~~~~~~~~
                                                   native_handle_t
In file included from gralloc.c:5:0:
/home/eclipse/lh/hybris_headers/hardware/gralloc.h:173:13: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
             buffer_handle_t handle);
             ^~~~~~~~~~~~~~~
             native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc.h:188:13: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
             buffer_handle_t handle);
             ^~~~~~~~~~~~~~~
             native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc.h:226:13: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
             buffer_handle_t handle, int usage,
             ^~~~~~~~~~~~~~~
             native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc.h:237:13: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
             buffer_handle_t handle);
             ^~~~~~~~~~~~~~~
             native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc.h:265:13: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
             buffer_handle_t handle, int usage,
             ^~~~~~~~~~~~~~~
             native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc.h:280:13: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
             buffer_handle_t handle, int usage,
             ^~~~~~~~~~~~~~~
             native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc.h:296:13: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
             buffer_handle_t handle, int* fenceFd);
             ^~~~~~~~~~~~~~~
             native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc.h:310:13: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
             buffer_handle_t handle, int usage,
             ^~~~~~~~~~~~~~~
             native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc.h:344:13: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
             buffer_handle_t* handle, int* stride);
             ^~~~~~~~~~~~~~~
             native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc.h:357:13: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
             buffer_handle_t handle);
             ^~~~~~~~~~~~~~~
             native_handle_t
In file included from gralloc.c:8:0:
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:539:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:561:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:583:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer, uint32_t* outWidth,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:605:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t descriptor,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:627:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:649:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:674:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer, uint32_t* outStride);
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:699:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer, uint32_t *outNumFds,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:731:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:786:9: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         buffer_handle_t* outBuffers);
         ^~~~~~~~~~~~~~~
         native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:816:42: error: unknown type name 'buffer_handle_t'
         gralloc1_device_t* device, const buffer_handle_t rawHandle,
                                          ^~~~~~~~~~~~~~~
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:817:9: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         buffer_handle_t* outBuffer);
         ^~~~~~~~~~~~~~~
         native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:840:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer);
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:865:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer);
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:903:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:963:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:1012:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:1041:36: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
         gralloc1_device_t* device, buffer_handle_t buffer,
                                    ^~~~~~~~~~~~~~~
                                    native_handle_t
In file included from gralloc.c:16:0:
../include/hybris/gralloc/gralloc.h:19:28: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_release(buffer_handle_t handle, int was_allocated);
                            ^~~~~~~~~~~~~~~
                            native_handle_t
../include/hybris/gralloc/gralloc.h:20:27: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_retain(buffer_handle_t handle);
                           ^~~~~~~~~~~~~~~
                           native_handle_t
../include/hybris/gralloc/gralloc.h:21:75: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_allocate(int width, int height, int format, int usage, buffer_handle_t *handle, uint32_t *stride);
                                                                           ^~~~~~~~~~~~~~~
                                                                           native_handle_t
../include/hybris/gralloc/gralloc.h:22:25: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_lock(buffer_handle_t handle, int usage, int l, int t, int w, int h, void **vaddr);
                         ^~~~~~~~~~~~~~~
                         native_handle_t
../include/hybris/gralloc/gralloc.h:23:27: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_unlock(buffer_handle_t handle);
                           ^~~~~~~~~~~~~~~
                           native_handle_t
../include/hybris/gralloc/gralloc.h:27:31: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_fbdev_post(buffer_handle_t handle);
                               ^~~~~~~~~~~~~~~
                               native_handle_t
gralloc.c:44:8: error: unknown type name 'GRALLOC1_PFN_GET_BACKING_STORE'
 static GRALLOC1_PFN_GET_BACKING_STORE gralloc1_get_backing_store = NULL;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gralloc.c:44:68: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_GET_BACKING_STORE gralloc1_get_backing_store = NULL;
                                                                    ^~~~
gralloc.c:45:8: error: unknown type name 'GRALLOC1_PFN_GET_CONSUMER_USAGE'
 static GRALLOC1_PFN_GET_CONSUMER_USAGE gralloc1_get_consumer_usage = NULL;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gralloc.c:45:70: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_GET_CONSUMER_USAGE gralloc1_get_consumer_usage = NULL;
                                                                      ^~~~
gralloc.c:46:8: error: unknown type name 'GRALLOC1_PFN_GET_DIMENSIONS'
 static GRALLOC1_PFN_GET_DIMENSIONS gralloc1_get_dimensions = NULL;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
gralloc.c:46:62: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_GET_DIMENSIONS gralloc1_get_dimensions = NULL;
                                                              ^~~~
gralloc.c:47:8: error: unknown type name 'GRALLOC1_PFN_GET_FORMAT'
 static GRALLOC1_PFN_GET_FORMAT gralloc1_get_format = NULL;
        ^~~~~~~~~~~~~~~~~~~~~~~
gralloc.c:47:54: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_GET_FORMAT gralloc1_get_format = NULL;
                                                      ^~~~
gralloc.c:48:8: error: unknown type name 'GRALLOC1_PFN_GET_PRODUCER_USAGE'
 static GRALLOC1_PFN_GET_PRODUCER_USAGE gralloc1_get_producer_usage = NULL;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gralloc.c:48:70: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_GET_PRODUCER_USAGE gralloc1_get_producer_usage = NULL;
                                                                      ^~~~
gralloc.c:49:8: error: unknown type name 'GRALLOC1_PFN_GET_STRIDE'
 static GRALLOC1_PFN_GET_STRIDE gralloc1_get_stride = NULL;
        ^~~~~~~~~~~~~~~~~~~~~~~
gralloc.c:49:54: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_GET_STRIDE gralloc1_get_stride = NULL;
                                                      ^~~~
gralloc.c:50:8: error: unknown type name 'GRALLOC1_PFN_ALLOCATE'
 static GRALLOC1_PFN_ALLOCATE gralloc1_allocate = NULL;
        ^~~~~~~~~~~~~~~~~~~~~
gralloc.c:50:50: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_ALLOCATE gralloc1_allocate = NULL;
                                                  ^~~~
gralloc.c:51:8: error: unknown type name 'GRALLOC1_PFN_RETAIN'
 static GRALLOC1_PFN_RETAIN gralloc1_retain = NULL;
        ^~~~~~~~~~~~~~~~~~~
gralloc.c:51:46: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_RETAIN gralloc1_retain = NULL;
                                              ^~~~
gralloc.c:52:8: error: unknown type name 'GRALLOC1_PFN_RELEASE'
 static GRALLOC1_PFN_RELEASE gralloc1_release = NULL;
        ^~~~~~~~~~~~~~~~~~~~
gralloc.c:52:48: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_RELEASE gralloc1_release = NULL;
                                                ^~~~
gralloc.c:53:8: error: unknown type name 'GRALLOC1_PFN_GET_NUM_FLEX_PLANES'
 static GRALLOC1_PFN_GET_NUM_FLEX_PLANES gralloc1_get_num_flex_planes = NULL;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gralloc.c:53:72: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_GET_NUM_FLEX_PLANES gralloc1_get_num_flex_planes = NULL;
                                                                        ^~~~
gralloc.c:54:8: error: unknown type name 'GRALLOC1_PFN_LOCK'
 static GRALLOC1_PFN_LOCK gralloc1_lock = NULL;
        ^~~~~~~~~~~~~~~~~
gralloc.c:54:42: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_LOCK gralloc1_lock = NULL;
                                          ^~~~
gralloc.c:55:8: error: unknown type name 'GRALLOC1_PFN_LOCK_FLEX'
 static GRALLOC1_PFN_LOCK_FLEX gralloc1_lock_flex = NULL;
        ^~~~~~~~~~~~~~~~~~~~~~
gralloc.c:55:52: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_LOCK_FLEX gralloc1_lock_flex = NULL;
                                                    ^~~~
gralloc.c:56:8: error: unknown type name 'GRALLOC1_PFN_UNLOCK'
 static GRALLOC1_PFN_UNLOCK gralloc1_unlock = NULL;
        ^~~~~~~~~~~~~~~~~~~
gralloc.c:56:46: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GRALLOC1_PFN_UNLOCK gralloc1_unlock = NULL;
                                              ^~~~
gralloc.c: In function 'gralloc1_init':
gralloc.c:187:35: error: 'GRALLOC1_PFN_GET_BACKING_STORE' undeclared (first use in this function); did you mean 'GRALLOC1_FUNCTION_GET_BACKING_STORE'?
     gralloc1_get_backing_store = (GRALLOC1_PFN_GET_BACKING_STORE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_BACKING_STORE);
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   GRALLOC1_FUNCTION_GET_BACKING_STORE
gralloc.c:187:35: note: each undeclared identifier is reported only once for each function it appears in
gralloc.c:187:66: error: expected ';' before 'gralloc1_device'
     gralloc1_get_backing_store = (GRALLOC1_PFN_GET_BACKING_STORE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_BACKING_STORE);
                                                                  ^~~~~~~~~~~~~~~
gralloc.c:188:36: error: 'GRALLOC1_PFN_GET_CONSUMER_USAGE' undeclared (first use in this function); did you mean 'GRALLOC1_PFN_SET_CONSUMER_USAGE'?
     gralloc1_get_consumer_usage = (GRALLOC1_PFN_GET_CONSUMER_USAGE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_CONSUMER_USAGE);
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                    GRALLOC1_PFN_SET_CONSUMER_USAGE
gralloc.c:188:68: error: expected ';' before 'gralloc1_device'
     gralloc1_get_consumer_usage = (GRALLOC1_PFN_GET_CONSUMER_USAGE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_CONSUMER_USAGE);
                                                                    ^~~~~~~~~~~~~~~
gralloc.c:189:32: error: 'GRALLOC1_PFN_GET_DIMENSIONS' undeclared (first use in this function); did you mean 'GRALLOC1_PFN_SET_DIMENSIONS'?
     gralloc1_get_dimensions = (GRALLOC1_PFN_GET_DIMENSIONS)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_DIMENSIONS);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                GRALLOC1_PFN_SET_DIMENSIONS
gralloc.c:189:60: error: expected ';' before 'gralloc1_device'
     gralloc1_get_dimensions = (GRALLOC1_PFN_GET_DIMENSIONS)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_DIMENSIONS);
                                                            ^~~~~~~~~~~~~~~
gralloc.c:190:28: error: 'GRALLOC1_PFN_GET_FORMAT' undeclared (first use in this function); did you mean  GRALLOC1_PFN_SET_FORMAT'?
     gralloc1_get_format = (GRALLOC1_PFN_GET_FORMAT)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_FORMAT);
                            ^~~~~~~~~~~~~~~~~~~~~~~
                            GRALLOC1_PFN_SET_FORMAT
gralloc.c:190:52: error: expected ';' before 'gralloc1_device'
     gralloc1_get_format = (GRALLOC1_PFN_GET_FORMAT)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_FORMAT);
                                                    ^~~~~~~~~~~~~~~
gralloc.c:191:36: error: 'GRALLOC1_PFN_GET_PRODUCER_USAGE' undeclared (first use in this function); did you mean 'GRALLOC1_PFN_SET_PRODUCER_USAGE'?
     gralloc1_get_producer_usage = (GRALLOC1_PFN_GET_PRODUCER_USAGE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_PRODUCER_USAGE);
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                    GRALLOC1_PFN_SET_PRODUCER_USAGE
gralloc.c:191:68: error: expected ';' before 'gralloc1_device'
     gralloc1_get_producer_usage = (GRALLOC1_PFN_GET_PRODUCER_USAGE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_PRODUCER_USAGE);
                                                                    ^~~~~~~~~~~~~~~
gralloc.c:192:28: error: 'GRALLOC1_PFN_GET_STRIDE' undeclared (first use in this function); did you mean  GRALLOC1_PFN_GET_FORMAT'?
     gralloc1_get_stride = (GRALLOC1_PFN_GET_STRIDE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_STRIDE);
                            ^~~~~~~~~~~~~~~~~~~~~~~
                            GRALLOC1_PFN_GET_FORMAT
gralloc.c:192:52: error: expected ';' before 'gralloc1_device'
     gralloc1_get_stride = (GRALLOC1_PFN_GET_STRIDE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_STRIDE);
                                                    ^~~~~~~~~~~~~~~
gralloc.c:193:26: error: 'GRALLOC1_PFN_ALLOCATE' undeclared (first use in this function); did you mean 'GRALLOC1_FUNCTION_ALLOCATE'?
     gralloc1_allocate = (GRALLOC1_PFN_ALLOCATE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_ALLOCATE);
                          ^~~~~~~~~~~~~~~~~~~~~
                          GRALLOC1_FUNCTION_ALLOCATE
gralloc.c:193:48: error: expected ';' before 'gralloc1_device'
     gralloc1_allocate = (GRALLOC1_PFN_ALLOCATE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_ALLOCATE);
                                                ^~~~~~~~~~~~~~~
gralloc.c:194:24: error: 'GRALLOC1_PFN_RETAIN' undeclared (first use in this function); did you mean 'GRALLOC1_PFN_DUMP'?
     gralloc1_retain = (GRALLOC1_PFN_RETAIN)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_RETAIN);
                        ^~~~~~~~~~~~~~~~~~~
                        GRALLOC1_PFN_DUMP
gralloc.c:194:44: error: expected ';' before 'gralloc1_device'
     gralloc1_retain = (GRALLOC1_PFN_RETAIN)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_RETAIN);
                                            ^~~~~~~~~~~~~~~
gralloc.c:195:25: error: 'GRALLOC1_PFN_RELEASE' undeclared (first use in this function); did you mean 'GRALLOC1_PFN_RETAIN'?
     gralloc1_release = (GRALLOC1_PFN_RELEASE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_RELEASE);
                         ^~~~~~~~~~~~~~~~~~~~
                         GRALLOC1_PFN_RETAIN
gralloc.c:195:46: error: expected ';' before 'gralloc1_device'
     gralloc1_release = (GRALLOC1_PFN_RELEASE)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_RELEASE);
                                              ^~~~~~~~~~~~~~~
gralloc.c:196:37: error: 'GRALLOC1_PFN_GET_NUM_FLEX_PLANES' undeclared (first use in this function); did you mean 'GRALLOC1_FUNCTION_GET_NUM_FLEX_PLANES'?
     gralloc1_get_num_flex_planes = (GRALLOC1_PFN_GET_NUM_FLEX_PLANES)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_NUM_FLEX_PLANES);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                     GRALLOC1_FUNCTION_GET_NUM_FLEX_PLANES
gralloc.c:196:70: error: expected ';' before 'gralloc1_device'
     gralloc1_get_num_flex_planes = (GRALLOC1_PFN_GET_NUM_FLEX_PLANES)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_GET_NUM_FLEX_PLANES);
                                                                      ^~~~~~~~~~~~~~~
gralloc.c:197:22: error: 'GRALLOC1_PFN_LOCK' undeclared (first use in this function); did you mean 'GRALLOC1_PFN_DUMP'?
     gralloc1_lock = (GRALLOC1_PFN_LOCK)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_LOCK);
                      ^~~~~~~~~~~~~~~~~
                      GRALLOC1_PFN_DUMP
gralloc.c:197:40: error: expected ';' before 'gralloc1_device'
     gralloc1_lock = (GRALLOC1_PFN_LOCK)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_LOCK);
                                        ^~~~~~~~~~~~~~~
gralloc.c:198:27: error: 'GRALLOC1_PFN_LOCK_FLEX' undeclared (first use in this function); did you mean 'GRALLOC1_PFN_LOCK'?
     gralloc1_lock_flex = (GRALLOC1_PFN_LOCK_FLEX)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_LOCK_FLEX);
                           ^~~~~~~~~~~~~~~~~~~~~~
                           GRALLOC1_PFN_LOCK
gralloc.c:198:50: error: expected ';' before 'gralloc1_device'
     gralloc1_lock_flex = (GRALLOC1_PFN_LOCK_FLEX)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_LOCK_FLEX);
                                                  ^~~~~~~~~~~~~~~
gralloc.c:199:24: error: 'GRALLOC1_PFN_UNLOCK' undeclared (first use in this function); did you mean 'GRALLOC1_PFN_LOCK'?
     gralloc1_unlock = (GRALLOC1_PFN_UNLOCK)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_UNLOCK);
                        ^~~~~~~~~~~~~~~~~~~
                        GRALLOC1_PFN_LOCK
gralloc.c:199:44: error: expected ';' before 'gralloc1_device'
     gralloc1_unlock = (GRALLOC1_PFN_UNLOCK)gralloc1_device->getFunction(gralloc1_device, GRALLOC1_FUNCTION_UNLOCK);
                                            ^~~~~~~~~~~~~~~
gralloc.c: At top level:
gralloc.c:207:28: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_release(buffer_handle_t handle, int was_allocated)
                            ^~~~~~~~~~~~~~~
                            native_handle_t
gralloc.c:236:27: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_retain(buffer_handle_t handle)
                           ^~~~~~~~~~~~~~~
                           native_handle_t
gralloc.c:249:75: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_allocate(int width, int height, int format, int usage, buffer_handle_t *handle_ptr, uint32_t *stride_ptr)
                                                                           ^~~~~~~~~~~~~~~
                                                                           native_handle_t
gralloc.c:282:25: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_lock(buffer_handle_t handle, int usage, int l, int t, int w, int h, void **vaddr)
                         ^~~~~~~~~~~~~~~
                         native_handle_t
gralloc.c:306:27: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_unlock(buffer_handle_t handle)
                           ^~~~~~~~~~~~~~~
                           native_handle_t
gralloc.c:340:31: error: unknown type name 'buffer_handle_t'; did you mean 'native_handle_t'?
 int hybris_gralloc_fbdev_post(buffer_handle_t handle)
                               ^~~~~~~~~~~~~~~
                               native_handle_t
Makefile:497: recipe for target 'libgralloc_la-gralloc.lo' failed
make[2]: *** [libgralloc_la-gralloc.lo] Error 1
make[2]: Leaving directory '/home/eclipse/lh/libhybris/hybris/gralloc'
Makefile:427: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/eclipse/lh/libhybris/hybris'
Makefile:359: recipe for target 'all' failed
make: *** [all] Error 2
root@localhost:/home/eclipse/lh/libhybris/hybris#

If i change buffer_handle_t to native_handle_t in files then i get this

eclipse@localhost:~/lh/libhybris/hybris$ make
make  all-recursive
make[1]: Entering directory '/home/eclipse/lh/libhybris/hybris'
Making all in include
make[2]: Entering directory '/home/eclipse/lh/libhybris/hybris/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/eclipse/lh/libhybris/hybris/include'
Making all in common
make[2]: Entering directory '/home/eclipse/lh/libhybris/hybris/common'
Making all in jb
make[3]: Entering directory '/home/eclipse/lh/libhybris/hybris/common/jb'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/eclipse/lh/libhybris/hybris/common/jb'
make[3]: Entering directory '/home/eclipse/lh/libhybris/hybris/common'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/eclipse/lh/libhybris/hybris/common'
make[2]: Leaving directory '/home/eclipse/lh/libhybris/hybris/common'
Making all in properties
make[2]: Entering directory '/home/eclipse/lh/libhybris/hybris/properties'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/eclipse/lh/libhybris/hybris/properties'
Making all in hardware
make[2]: Entering directory '/home/eclipse/lh/libhybris/hybris/hardware'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/eclipse/lh/libhybris/hybris/hardware'
Making all in gralloc
make[2]: Entering directory '/home/eclipse/lh/libhybris/hybris/gralloc'
  CC       libgralloc_la-gralloc.lo
In file included from gralloc.c:8:0:
/home/eclipse/lh/hybris_headers/hardware/gralloc1.h:1016:16: warning: ‘struct android_flex_layout’ declared inside parameter list will not be visible outside of
 this definition or declaration
         struct android_flex_layout* outFlexLayout, int32_t acquireFence);
                ^~~~~~~~~~~~~~~~~~~
gralloc.c: In function ‘hybris_gralloc_release’:
gralloc.c:211:5: error: cannot convert to a pointer type
     if GRALLOC1(
     ^~
gralloc.c:211:5: error: cannot convert to a pointer type
gralloc.c:211:5: error: cannot convert to a pointer type
gralloc.c:211:5: error: cannot convert to a pointer type
Makefile:497: recipe for target 'libgralloc_la-gralloc.lo' failed
make[2]: *** [libgralloc_la-gralloc.lo] Error 1
make[2]: Leaving directory '/home/eclipse/lh/libhybris/hybris/gralloc'
Makefile:427: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/eclipse/lh/libhybris/hybris'
Makefile:359: recipe for target 'all' failed
make: *** [all] Error 2
eclipse@localhost:~/lh/libhybris/hybris$

**Comment by e-cl** [comment]
Sorry. Please delete this

**Comment by carTloyal123** [comment]
How did you fix this issue? I am also having a similar problem when running make
