### ISSUE TITLE
Missing libwayland-egl.la

### ISSUE THREAD

**Issue by tadryanom** [libhybris/libhybris#421]
Hi!
I'm with problems when compile the libhybris. The build breaks in this stage:

Making all in tests
make[2]: Entering directory '/home/pi/devel/libhybris/hybris/tests'
  CC       test_audio-test_audio.o
  CCLD     test_audio
  CC       test_egl-test_egl.o
  CCLD     test_egl
  CC       test_egl_configs-test_egl_configs.o
  CCLD     test_egl_configs
  CC       test_glesv2-test_glesv2.o
  CCLD     test_glesv2
  CC       test_sf-test_sf.o
  CCLD     test_sf
  CC       test_sensors-test_sensors.o
  CCLD     test_sensors
  CC       test_input-test_input.o
  CCLD     test_input
  CC       test_lights-test_lights.o
  CCLD     test_lights
  CC       test_camera-test_camera.o
make[2]: *** No rule to make target '../egl/platforms/common/libwayland-egl.la', needed by 'test_camera'.  Stop.
make[2]: Leaving directory '/home/pi/devel/libhybris/hybris/tests'

Can anyone tell me what is going on?

**Comment by mlehtima** [comment]
Do you have wayland development packages installed in your build environment? It seems that test program requires wayland to be present.

**Comment by tadryanom** [comment]
> Do you have wayland development packages installed in your build environment? It seems that test program requires wayland to be present.

Not sure which package to install Wayland for Debian. I've searched for packages containing this file and found none.

**Comment by mlehtima** [comment]
I meant that you need to have libwayland-dev package installed on your build environment. That package is available for installation using normal debian package managers.

**Comment by tadryanom** [comment]
> I meant that you need to have libwayland-dev package installed on your build environment. That package is available for installation using normal debian package managers.

I already have this packages installed, but I still have the problem.

pi@rasptulio01:~/devel/libhybris/hybris $ dpkg -l libwayland-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                    Architecture              Description
+++-=========================================-=========================-=========================-========================================================================================
ii  libwayland-dev:armhf                      1.12.0-1+deb9u1           armhf                     wayland compositor infrastructure - development files
pi@rasptulio01:~/devel/libhybris/hybris $ dpkg -L libwayland-dev
/.
/usr
/usr/include
/usr/include/wayland-client-core.h
/usr/include/wayland-client-protocol.h
/usr/include/wayland-client.h
/usr/include/wayland-cursor.h
/usr/include/wayland-egl-core.h
/usr/include/wayland-egl.h
/usr/include/wayland-server-core.h
/usr/include/wayland-server-protocol.h
/usr/include/wayland-server.h
/usr/include/wayland-util.h
/usr/include/wayland-version.h
/usr/lib
/usr/lib/arm-linux-gnueabihf
/usr/lib/arm-linux-gnueabihf/libwayland-client.a
/usr/lib/arm-linux-gnueabihf/libwayland-cursor.a
/usr/lib/arm-linux-gnueabihf/libwayland-server.a
/usr/lib/arm-linux-gnueabihf/pkgconfig
/usr/lib/arm-linux-gnueabihf/pkgconfig/wayland-client.pc
/usr/lib/arm-linux-gnueabihf/pkgconfig/wayland-cursor.pc
/usr/lib/arm-linux-gnueabihf/pkgconfig/wayland-scanner.pc
/usr/lib/arm-linux-gnueabihf/pkgconfig/wayland-server.pc
/usr/share
/usr/share/doc
/usr/share/doc/libwayland-dev
/usr/share/doc/libwayland-dev/changelog.Debian.gz
/usr/share/doc/libwayland-dev/copyright
/usr/share/wayland
/usr/share/wayland/wayland.dtd
/usr/share/wayland/wayland.xml
/usr/lib/arm-linux-gnueabihf/libwayland-client.so
/usr/lib/arm-linux-gnueabihf/libwayland-cursor.so
/usr/lib/arm-linux-gnueabihf/libwayland-server.so

**Comment by mlehtima** [comment]
Did the configure step of the build report that it found wayland? It should list everything it uses like "checking for WAYLAND_CLIENT" and so on. There should three of those WAYLAND_CLIENT, WAYLAND_SERVER and wayland-scanner. Did it find any of those?

**Comment by tadryanom** [comment]
> Did the configure step of the build report that it found wayland? It should list everything it uses like "checking for WAYLAND_CLIENT" and so on. There should three of those WAYLAND_CLIENT, WAYLAND_SERVER and wayland-scanner. Did it find any of those?

I left wayland off by default. I ran this command on the terminal:
`PKG_CONFIG_PATH=/home/pi/Android/lib/pkgconfig ./configure --prefix=/home/pi/Android2`
In "checking for ..." no mention of WAYLAND_ *. The summary of the process performed by the command was this:
`------------------------------------------------------------------------`
`libhybris 0.1.0`
`------------------------------------------------------------------------`
`Configuration Options:`
`  debug build.............: no`
`  trace...................: no`
`  experimental features...: no`
`  prefix..................: /home/pi/Android2`
`  arch  ..................: arm`
`  headers path ...........:` 
`  Android version.........: 5.1.1`
`  default egl platform ...: null`
`  default ld_library_path.: /vendor/lib:/system/lib:/odm/lib`
`Features:`
`  stub linker.............: no`
`  Ubuntu linker overrides.: no`
`------------------------------------------------------------------------`
