### ISSUE TITLE
Loading shared library linked against ld-linux.so

### ISSUE THREAD

**Issue by nindolabs** [libhybris/libhybris#431]
Hello,

I'm trying to find a solution to load libEGL.so and libGLESv...so of nvidia which are linked against ld.so and glibc in hwcomposer and gralloc which are linked against bionic.

Is it possible to do this through libhybris ? i need to avoid using some rpc mecanism to use nvidia linux drivers inside an android container.

Thank you for your help.

**Comment by krnlyng** [comment]
@nindolabs libhybris does the opposite, load android libraries in glibc space.

I am not aware of any implementation which does what you need unfortunately :(.

**Comment by nindolabs** [comment]
Thanks for your reply.
