### ISSUE TITLE
Race condition when using SDL2/Wayland

### ISSUE THREAD

**Issue by fcipaq** [libhybris/libhybris#443]
I am using libhybris on a x86 Android tablet with PowerVR graphics to run KWin-Wayland with Plasma desktop (Debian). The desktop is working well.
I am trying to use a program, namely "Neverball", a (famous?) opensource game from the Debian repo, with SDL2/wayland support.

Program start fails with 

`gralloc.c:132: hybris_gralloc_initialize: Assertion `NULL' failed.`

Now, this is due to two calls the SDL lib makes to libhybris:

1. `eglQueryString` which then calls `_init_ws();` in `ws.c`
2. While still in `_init_ws();` libhybis gets a second call to `GetDisplay` and again, `_init_ws();` is being calld.
3. Because the first call to `_init_ws();` has not yet completed causes a double call on `hybris_gralloc_initialize` eventually leading to the error message above.

I am not sure if this a SDL2 bug or libhybris bug, but a solution that worked for me, was a mutex approach in `ws.c`:

```
static struct ws_module *ws = NULL;
static int ws_init_locked = 0;

static void _init_ws()
{
	do {} while (ws_init_locked)

	if (ws == NULL)
	{
         ws_init_locked = 1;
         ...
         ws_init_locked = 0;
	}
}

```
In fact I am unsure why there even is a call from the SDL2 side to `GetDisplay` before `eglQueryString` has finished...

**Comment by fcipaq** [comment]
Another solution that worked for me is to make multiple calls to `hybris_gralloc_initialize` non fatal. I.e. replace the assertion by a warning:

https://github.com/libhybris/libhybris/blob/master/hybris/gralloc/gralloc.c#L132

I do not see any harm here as the code does in case `version != -1`

**Comment by krnlyng** [comment]
looks like a libhybris bug: "EGL and its client APIs must be threadsafe." from https://www.khronos.org/registry/EGL/specs/eglspec.1.4.withchanges.pdf

**Comment by fcipaq** [comment]
Thanks, that sound reasonable. I'll test it and if it works, I'll MR.

**Comment by krnlyng** [comment]
@fcipaq i guess we can close this now?
