### ISSUE TITLE
operator.new not being executed correctly

### ISSUE THREAD

**Issue by cernec1999** [libhybris/libhybris#475]
Forgive my ignorance if this is an easy fix. I am rather new to libhybris and I am using it as a means to run an x86_64 NDK-compiled binary on my x86_64 Linux glibc system (the binary is also linked against libGLESv1_CM.so).

I have been investigating a crash from a dynamically linked shared object file, in the DT_INIT_ARRAY function. Fortunately, it seems I have built libhybris correctly and it appears to be executing some functions correctly. The problem occurs when the library I am using calls operator.new (_Znwm). This function is supposed to return a pointer to valid memory, but instead, it returns a null pointer and results in a null pointer dereference in my application.

I stepped into _Znwm, and it seems that the libhybris linker is not correctly linking the libstdc++ function. I have tested this with my own source code:
```
struct TestClass {
    int a;
    int b;
};

void * test(int a, int b) {
    TestClass * p1 = new TestClass;
    p1->a = 5;
    p1->b = 6;
    return (void *) p1;
}
```
Compilation command: `android23-clang++ -shared -o libtest.so libtest.cpp -fno-exceptions -O0 -stdlib=libstdc++`

Run (a quick aside: the trace statements don't appear to show up, even with --enable-trace compile flag):
```
HYBRIS_TRACE=1 HYBRIS_LOGGING_LEVEL=debug HYBRIS_LD_DEBUG=1 ./HybrisTest
HOOKS hooks.c:3337 (__hybris_linker_init) DEBUG: Linker initialization
HOOKS hooks.c:3234 (get_android_sdk_version) DEBUG: Using SDK API version 23

HOOKS hooks.c:3387 (__hybris_linker_init) DEBUG: Loading linker from /opt/libhybris/lib/libhybris/linker/mm.so..
[ linking /home/ccerne/HybrisTest/lib/x86_64/libtest.so ]
[ linking /system/lib64/libstdc++.so ]
[ linking /system/lib64/libm.so ]
[ linking /system/lib64/libc.so ]
HOOKS hooks.c:3315 (__hybris_get_hooked_symbol) DEBUG: Could not find a hook for symbol __register_atfork
HOOKS hooks.c:3315 (__hybris_get_hooked_symbol) DEBUG: Could not find a hook for symbol _Znwm
Segmentation fault (core dumped)
```

![image](https://user-images.githubusercontent.com/5413945/107545992-e325b680-6b99-11eb-9ed1-76d7edec33c4.png)

Please note the `$rax` register not updating. It is the same value before the function call to 0x7ffff7f7f5d0 (which is supposed to be operator.new)

I assume it has something to do with:
```
HOOKS hooks.c:3315 (__hybris_get_hooked_symbol) DEBUG: Could not find a hook for symbol _Znwm
```

How can I fix this?

**Comment by krnlyng** [comment]
HOOKS hooks.c:3315 (__hybris_get_hooked_symbol) DEBUG: Could not find a hook for symbol _Znwm

this is not an error it just means that the function will be used from your library and will not be replaces.

Just because this is a common case, did you patch libc.so? it is required to patch libc.so with hybris-patches.

**Comment by cernec1999** [comment]
Thank you for the quick response! Unfortunately, I've been out of the loop with the hybris process, and I couldn't find a good guide to getting started. I assume this is the repository you're referring to: https://github.com/mer-hybris/hybris-patches. I suppose I should use the branch `hybris-17.1`?

I alkso noticed that this project is mainly for Linux glibc smartphones (like SailfishOS). I can still use this for a Linux virtual machine, correct (like Ubuntu)?

**Comment by krnlyng** [comment]
hybris-17.1 is based on the corresponding lineageos version, you might have to rebase the patches to apply to your android base.

The frameworks/native patches take care of being able to load the gles libraries, however it would require that your kernel etc understands what the android versions of the gles versions want to do.

Your usecase sounds a bit more like a case for apkenv or something similar, but apkenv's codebase is rather old, but i am not sure what your actual usecase (?) is, so i am unsure about that statement.

**Comment by cernec1999** [comment]
My use case is actually reverse engineering / researching the protocol of a video game. My goal was to hopefully be able to run the x86_64 binaries on my machine without using an android emulator, to make the task at hand a little easier (i.e. attaching a debugger), but I suppose it may be more trouble than it's worth.

Thank you for the suggestion of apkenv. I actually saw that in reference to an issue here, but I agree with you that the codebase is rather old.

Because of my inexperience with the Android operating system, I may just forgo this side project for now and just stick with an emulator. Thank you for your thoughts, and best of luck with SailfishOS development!
