### ISSUE TITLE
HOW TO CPMPILE IT???

### ISSUE THREAD

**Issue by dontknowhy** [libhybris/libhybris#510]
so i runned autogen.sh
and then sudo ./configure --enable-experimental --enable-adreno-quirks --enable-mesa --enable-ubuntu-camera-headers --enable-wayland --enable-glvnd --enable-wayland_serverside_buffers --enable-property-cache --enable-ubuntu-linker-overrides --enable-mali-quirks --enable-stub-linker
but Makefile doesn't show up
how can i do?(android header???)
![Screenshot_20220507_223736.jpg](https://user-images.githubusercontent.com/85813508/167258996-93e62586-6b12-4236-a1d6-7ebdc6214034.jpg)

**Comment by dontknowhy** [comment]
with fantastic bing
i'm now configuring this…

**Comment by dontknowhy** [comment]
i'm back
debian doesn't have platformcommon.h
i don't want to download android's sources code because i'm using a phone.
how can i compile it?

**Comment by mlehtima** [comment]
platformcommon.h is in https://github.com/libhybris/libhybris/tree/master/hybris/platforms/common how does your build fail?

**Comment by dontknowhy** [comment]
> platformcommon.h is in https://github.com/libhybris/libhybris/tree/master/hybris/platforms/common how does your build fail?

i don't know…
![Screenshot_20220508_092155.jpg](https://user-images.githubusercontent.com/85813508/167277885-b775102e-f776-4cff-92e8-b8585cc1252c.jpg)

**Comment by dontknowhy** [comment]
> platformcommon.h is in https://github.com/libhybris/libhybris/tree/master/hybris/platforms/common how does your build fail?

copy the platforncommon.h to /home/dontknowhy/libhybris/hybris/egl
and done
WHY???

**Comment by mlehtima** [comment]
Can you test building with the changes in https://github.com/libhybris/libhybris/issues/510?

**Comment by dontknowhy** [comment]
> Can you test building with the changes in https://github.com/libhybris/libhybris/pull/511?

i completed the codes
and the test program said: TLS relocations not yet implemented in libhybriszsh: abort      test_gps
???
how to fix it
(my android device has been detected but can't use it because i don't have root)
