### ISSUE TITLE
How do I load Bionic libraries that depend on libc?

### ISSUE THREAD

**Issue by william-stacken** [libhybris/libhybris#521]
My use case is that I have a shared library dependent on libc, libdl and a number of other bionic libraries, that I would like to run on a glibc system. I have tried loading the bionic libc, but it expectedly does not work since libhybris seems to specifically reject calling its initialization vectors. This means that the global environment variable remains uninitialized which leads to a segmentation fault when calling "setenv". I also noticed that libhybris intercepts any request to dlopen libdl.so, and returns itself. If this is the case, then shouldn't it also do something simliar for libc.so, that is, return the glibc libc.so that libhybris-common.so itself depends on?

**Comment by william-stacken** [comment]
I managed to come up with a solution. I edited [this line](https://github.com/libhybris/libhybris/blob/master/hybris/common/jb/dlfcn.c#L285) from `name: "libdl.so"`, to `name: ""libhybris-common.so.1"`. Then I compiled and used "libc.so" from [fake_libc](https://github.com/krnlyng/fake_libc) (although I had to edit it lots to get it working). Then I also used libdl.so from fake_libc, but edited it such that it calls libhybris's "android_dl*" functions instead. I also had to implement a hack in libhybris's [linker.c](https://github.com/libhybris/libhybris/blob/master/hybris/common/jb/linker.c) to allow it to relay calls to dlopen and dlsym to the glib libdl.so for libraries it cannot find. This allowed for loading the fake libc's dependency on the glib libdl.

When I have time I'll fork libhybris and fake_libc and upload my changes there.

**Comment by krnlyng** [comment]
Usually you would patch bionic libc to avoid these issues: https://github.com/mer-hybris/hybris-patches. And the hooks from hooks.c should be used for functions that would fail in bionic libc. fake_libc is something else, it can be used as a libhybris replacement, but it isn't as flexible.

**Comment by carTloyal123** [comment]
This seems like a great issue and I think useful for many people in the community. From what I can tell you took a .so file from a plain Android APK and were able to use that .so file in your own gnu C program. Is that correct? Now you are able to convert your Android .so into a Linux/GNU .so? Please correct me wrong but I would much appreciate some more technical detail here as well if you would be able to share. I am also curious the steps you took to build libhybris correctly as I seem to be getting many build errors. Thanks!

**Comment by carTloyal123** [comment]
@william-stacken ^

**Comment by william-stacken** [comment]
> This seems like a great issue and I think useful for many people in the community.
Thank you for reminding me about this! Had completely forgotten.

> From what I can tell you took a .so file from a plain Android APK and were able to use that .so file in your own gnu C program. Is that correct?
Yes 😄 

> Now you are able to convert your Android .so into a Linux/GNU .so?
Not quite, I just used fake_libc and libhybris as a shim layer to get the Android .so to run on GNU/Linux.

> Please correct me wrong but I would much appreciate some more technical detail here as well if you would be able to share. I am also curious the steps you took to build libhybris correctly as I seem to be getting many build errors. Thanks!
I am quite busy right now, but I will dig up my local repositories and see if I can upload that fork. My .so was also armv7, so I had to spin up an armv7 debian VM in qemu to get it to run.
