### ISSUE TITLE
Windows-specific vulkan functions

### ISSUE THREAD

**Issue by muhammad23012009** [libhybris/libhybris#533]
Building libhybris on Ubuntu Touch results in this error: ‘vkAcquireWinrtDisplayNV’

```
vulkan.c:547:15: error: ‘vkAcquireWinrtDisplayNV’ undeclared here (not in a function); did you mean ‘vkAcquireDrmDisplayEXT’?
  547 | VULKAN_IDLOAD(vkAcquireWinrtDisplayNV);
      |               ^~~~~~~~~~~~~~~~~~~~~~~
vulkan.c:45:8: note: in definition of macro ‘VULKAN_IDLOAD’
   45 | typeof(sym) * sym ## _dispatch (void) __asm__ (#sym);\
      |        ^~~
vulkan.c:548:15: error: ‘vkGetWinrtDisplayNV’ undeclared here (not in a function)
  548 | VULKAN_IDLOAD(vkGetWinrtDisplayNV);
  ```
  
  From investigations these functions seem to be Windows-specific, as referred in https://github.com/KhronosGroup/Vulkan-Headers/blob/main/include/vulkan/vulkan.hpp#L5192
  This is only activated when building on windows here: https://github.com/KhronosGroup/Vulkan-Headers/blob/main/BUILD.gn#L22
  
  Why is this here if not needed? From what I've seen libhybris does not work on Windows, hence there is no need for this to be here.

**Comment by mlehtima** [comment]
Looks like those functions were in vulkan_core.h but those were moved to vulkan_win32.h in vulkan version 1.3.236. I added all functions which were in the core which is the reason why it broke now. I will fix it.

**Comment by mlehtima** [comment]
Fix in https://github.com/libhybris/libhybris/pull/534
