### ISSUE TITLE
TLS relocations not yet implemented in libhybrisBus error

### ISSUE THREAD

**Issue by fulinux** [libhybris/libhybris#556]
Hello, I'm using AOSP 13.0.0, and my build configuration is: ./autogen.sh --with-android-headers=/usr/local/include/android --enable-arch=arm64. After successful compilation, I encountered a new error when running the following command: 
test_dlopen /system/lib64/libc.so. 
TLS relocations not yet implemented in libhybrisBus error (core dumped)
Could you please advise on how to address this issue? Any guidance from an expert would be appreciated.

**Comment by krnlyng** [comment]
Usually that means you don't have hybris patches applied to bionic etc. Refer to https://github.com/mer-hybris/hybris-patches or the sailfish hadk https://docs.sailfishos.org/Develop/HADK/

**Comment by fulinux** [comment]
> Usually that means you don't have hybris patches applied to bionic etc. Refer to https://github.com/mer-hybris/hybris-patches or the sailfish hadk https://docs.sailfishos.org/Develop/HADK/
Thank you for your prompt response. I'll study the information you provided carefully. Thank you once again for your help.

**Comment by fulinux** [comment]
> Usually that means you don't have hybris patches applied to bionic etc. Refer to https://github.com/mer-hybris/hybris-patches or the sailfish hadk https://docs.sailfishos.org/Develop/HADK/

Dear @krnlyng ,
qssi]$ git clone https://github.com/mer-hybris/hybris-patches.git
qssi]$ cd hybris-patches/
hybris-patches]$ git checkout hybris-sony-aosp-13
hybris-patches]$ cd ..

After applying the patch you mentioned, I encountered compile errors:
...
e-generator/asm_defines.cc
In file included from art/tools/cpp-define-generator/asm_defines.cc:36:
In file included from art/tools/cpp-define-generator/asm_defines.def:21:
In file included from art/tools/cpp-define-generator/globals.def:24:
In file included from art/runtime/gc/heap.h:39:
In file included from art/runtime/gc/space/large_object_space.h:25:
art/runtime/thread-current-inl.h:37:56: error: expected expression
    void* thread = __get_tls()[TLS_SLOT_ART_THREAD_SELF];
                                                       ^
1 error generated.
[  0% 16/37812] //frameworks/native/opengl/libs:libEGL clang++ EGL/egl.cpp
[  0% 17/37812] //system/core/init:host_init_verifier clang++ subcontext.cpp [linux_glibc]
[  0% 18/37812] //frameworks/native/opengl/libs:libEGL clang++ EGL/eglApi.cpp
[  0% 19/37812] //system/core/init:host_init_verifier clang++ util.cpp [linux_glibc]
[  0% 20/37812] //frameworks/native/opengl/libs:libEGL clang++ EGL/egl_layers.cpp
[  0% 21/37812] //system/core/init:init_first_stage clang++ util.cpp
[  0% 22/37812] //frameworks/native/opengl/libs:libEGL header-abi-dumper EGL/egl_cache.cpp
[  0% 23/37812] //frameworks/native/opengl/libs:libEGL header-abi-dumper EGL/egl_object.cpp
[  0% 24/37812] //system/core/init:host_init_verifier clang++ host_init_verifier.cpp [linux_glibc]
[  0% 25/37812] //frameworks/native/opengl/libs:libEGL header-abi-dumper EGL/egl_display.cpp
ninja: build stopped: subcommand failed.
20:04:52 ninja failed with: exit status 1

#### failed to build some targets (08:40 (mm:ss)) ####
The error occurs here:
art/runtime/thread-current-inl.h:
inline Thread* Thread::Current() {
  // We rely on Thread::Current returning null for a detached thread, so it's not obvious
  // that we can replace this with a direct %fs access on x86.
  if (!is_started_) {
    return nullptr;
  } else {
#ifdef __BIONIC__
    void* thread = __get_tls()[TLS_SLOT_ART_THREAD_SELF];   //here
#else
    Thread* thread = Thread::self_tls_;
#endif
    return reinterpret_cast<Thread*>(thread);
  }
}

How should I modify it?

Thanks.

**Comment by fulinux** [comment]
Dear @krnlyng ,
    My problem has been resolved, thank you very much for your help.
